#!/bin/bash
# GitBrain Setup Script
# Usage: bash setup.sh <repo_url> [device_id]

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check arguments
if [ -z "$1" ]; then
    log_error "Usage: bash setup.sh <repo_url> [device_id]"
    log_error "Example: bash setup.sh https://github.com/user/gitbrain.git pc-win"
    exit 1
fi

REPO_URL="$1"
DEVICE_ID="${2:-$(hostname)}"
HERMES_DIR="$HOME/.hermes"
GITBRAIN_DIR="$HERMES_DIR/gitbrain"
CONFIG_FILE="$HERMES_DIR/gitbrain.yaml"

log_info "Setting up GitBrain..."
log_info "Repository: $REPO_URL"
log_info "Device ID: $DEVICE_ID"

# Step 1: Check prerequisites
log_info "Checking prerequisites..."

if ! command -v git &> /dev/null; then
    log_error "Git is not installed"
    exit 1
fi

if [ ! -d "$HERMES_DIR" ]; then
    log_error "Hermes directory not found at $HERMES_DIR"
    exit 1
fi

# Step 2: Configure git credentials if needed
log_info "Checking git credentials..."

if ! git config --global credential.helper | grep -q "store"; then
    log_warn "Git credential store not configured"
    log_info "Run: git config --global credential.helper store"
fi

# Step 3: Clone repository
log_info "Cloning repository..."

if [ -d "$GITBRAIN_DIR" ]; then
    log_warn "GitBrain directory already exists at $GITBRAIN_DIR"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Skipping clone"
    else
        rm -rf "$GITBRAIN_DIR"
        git clone "$REPO_URL" "$GITBRAIN_DIR"
    fi
else
    git clone "$REPO_URL" "$GITBRAIN_DIR"
fi

# Step 4: Create config file
log_info "Creating configuration..."

cat > "$CONFIG_FILE" << EOF
# GitBrain Configuration
# Auto-generated by setup.sh

repo_url: $REPO_URL
device_id: $DEVICE_ID
auto_pull: true
auto_push: true
sync_interval: 300

sync:
  skills: true
  memories: true
  config: false

conflict_strategy: timestamp
EOF

log_info "Config saved to $CONFIG_FILE"

# Step 5: Create directory structure
log_info "Creating directory structure..."

mkdir -p "$GITBRAIN_DIR/skills"
mkdir -p "$GITBRAIN_DIR/memories/shared"
mkdir -p "$GITBRAIN_DIR/memories/$DEVICE_ID"
mkdir -p "$GITBRAIN_DIR/config"

# Step 6: Initial sync
log_info "Performing initial sync..."

cd "$GITBRAIN_DIR"
git pull origin master 2>/dev/null || git pull origin main 2>/dev/null || true

# Step 7: Setup complete
log_info "Setup complete!"
echo
echo "Next steps:"
echo "1. Add sync script to Hermes SOUL.md:"
echo "   ## GitBrain Sync"
echo "   On startup: run ~/.hermes/gitbrain/scripts/sync.sh pull"
echo "   On change: run ~/.hermes/gitbrain/scripts/sync.sh push"
echo
echo "2. Manual sync:"
echo "   bash ~/.hermes/gitbrain/scripts/sync.sh [pull|push|sync]"
echo
echo "3. Configure device priority (optional):"
echo "   Edit $CONFIG_FILE"
